# Change these first
owner: Jim-Paul # Your GitHub organization or username, where this repository lives
repo: Upptime-Status # The name of this repository

sites:
  - name: Jim Paul
    url: https://jimpaul.ng
  - name: Terrawatt Energy
    url: https://terrawattenergy.io
  - name: Quantumica
    url: https://quantumica.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.quantumica.io
  #baseUrl: /Upptime-Status
  logoUrl: https://raw.githubusercontent.com/Jim-Paul/Upptime-Status/refs/heads/master/assets/QUATUMICA%2002.png
  name: Quantumica Status Page
  introTitle: "Welcome to the official status page for **Quantumica**, a forward-thinking company at the intersection of technology, real-estate and energy."
  introMessage: "This page offers **real-time insights** into the availability and performance of our platforms."

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Jim-Paul/Upptime-Status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
